version: "3.8"

services:
  product-service:
    build: ./productservice
    ports:
      - "8080:8080"
    networks:
      - common_network
    depends_on:
      - discovery-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8181/eureka/
      - SPRING_APPLICATION_NAME=product-service
  order-service:
    build: ./orderservice
    ports:
      - "8081:8081"
    networks:
      - common_network
    depends_on:
      - discovery-server
    environment:
      - spring.cloud.config.profile=prod
  discovery-server:
    build: ./discoveryserver
    ports:
      - "8181:8181"
    networks:
      - common_network
  gateway:
    build: ./gateway
    ports:
      - "8010:8010"
    depends_on:
      - discovery-server
    networks:
      - common_network
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8181/eureka/

networks:
  common_network:
