version: "3.8"

services:
  product-service:
    build: ./productservice
    ports:
      - "8080:8080"
    networks:
      - common_network
    depends_on:
      - discovery-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8181/eureka/
  order-service:
    build: ./orderservice
    ports:
      - "8081:8081"
    networks:
      - common_network
    depends_on:
      - discovery-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8181/eureka/
  discovery-server:
    build: ./discoveryserver
    ports:
      - "8181:8181"
    networks:
      - common_network

networks:
  common_network:

