version: "3.8"

services:
  product-service:
    build: ./productservice
    ports:
      - "8080:8080"
    networks:
      - common_network
    depends_on:
      - discovery-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8181/eureka/
      - SPRING_APPLICATION_NAME=product-service
  order-service:
    build: ./orderservice
    ports:
      - "8081:8081"
    #kubernetes K8s
    restart: on-failure
    # restart: unless-stopped # kullanıcı tarafından durdurulmadıysa
    # restart: always #kullanıcı dahi durdursa yeniden başlatır.
    networks:
      - common_network
    depends_on:
      - discovery-server
      - config-server
      - kafka
    environment:
      - CONFIGURL=http://config-server:8888
      - SPRING_CLOUD_CONFIG_PROFILE=prod
  discovery-server:
    build: ./discoveryserver
    ports:
      - "8181:8181"
    networks:
      - common_network
  gateway:
    build: ./gateway
    ports:
      - "8010:8010"
    depends_on:
      - discovery-server
    networks:
      - common_network
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8181/eureka/
  config-server:
    build: ./configserver
    ports:
      - "8888:8888"
    networks:
      - common_network
    environment:
      - SPRING_CLOUD_CONFIG_SERVER_GIT_URI=https://github.com/halitkalayci/etiya-microservices-configurations.git
      - SPRING_CLOUD_CONFIG_SERVER_GIT_DEFAULT-LABEL=master
  postgres:
    image: postgres
    ports:
      - "5435:5432"
    networks:
      - common_network
    environment:
      - POSTGRES_PASSWORD=test
    volumes:
      - postgresql-vol:/var/lib/postgresql/data
  zookeeper:
    image: confluentinc/cp-zookeeper
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
  kafka:
    image: confluentinc/cp-kafka
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
networks:
  common_network:
    driver: bridge

volumes:
  postgresql-vol:
    name: postgresql-vol
